### ISSUE TITLE
Cpu percentage calculation is not correct

### ISSUE THREAD

**Issue by thijsc** [appsignal/probes-rs#22]
Probably more fields need to be included in the calculation to get 100%.

**Comment by tombruijn** [comment]
It looks like you'll have to do some more calculations when you want to get the totals

This is how htop does it https://github.com/hishamhm/htop/blob/e0209da88faf3b390d71ff174065abd407abfdfd/ProcessList.c#L932-L956

(Found through this Q&A: http://stackoverflow.com/a/23376195/543643)

**Comment by thijsc** [comment]
We do only support kernel 2.6 at the moment, maybe that narrows it down?
