### ISSUE TITLE
Available memory is reported for host instead of guest on docker

### ISSUE THREAD

**Issue by tombruijn** [appsignal/probes-rs#25]
On docker containers the `cat /proc/meminfo` command returns the available memory of the host, not the container itself. This reports way too much memory for some users.

Good place to start:
- /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
- /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
## Issues
- https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/5692464740
- https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/5668661938

**Comment by roytomeij** [comment]
Another customer report: https://app.intercom.io/a/apps/yzor8gyw/inbox/roy@appsignal.com/conversations/5854561907

**Comment by wesoudshoorn** [comment]
We might've lost a customer over this. No follow-up after they tried something that looked useful to them but got a bug.

https://app.intercom.io/a/apps/yzor8gyw/companies/57b45c071fe1e348460000a9/conversations

**Comment by tombruijn** [comment]
Alright, big problem with the docker memory usage reporting. Seems like we can't reliably get all the memory usage data we want.

We get our data from `/proc`, and apparently "/proc in general is considered to be a mess."

If you fetch information from `/proc` the returned values are not containerized. Instead it just reports the data from the host.

There are one or two ways to get containerized data, but of course that's not standardized. In docker you can get some information from `/sys/fs/cgroup/memory/`, but on LXC (or at least on Heroku) you cannot.

Instead what they recommend is that you look through all running processes and combine the data, but I'm not quite sure how or if that's what we really want.

What we can also do is to add the option to just track one process. So we know just the information from your ruby server or your sidekiq process and show that instead. Then we won't know the hard-cap of how much memory a process can use until it hits the swap.

For more information on the subject: https://fabiokung.com/2014/03/13/memory-inside-linux-containers/

**Comment by tombruijn** [comment]
Will discuss for Q3 roadmap

**Comment by thijsc** [comment]
We're closing this one for now. We've researched this extensively and as far as we know there is no solution possible. Docker does not provide this information and the value in `/etc/proc` is incorrect.
