### ISSUE TITLE
Read container limits from AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by adamyeats** [appsignal/probes-rs#44]
We currently report a much larger amount of available memory on AWS Elastic Beanstalk than is available. As little control is available of the containers themselves, we'll need to see if AWS exposes these values at all.

**Comment by xadamy** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/search/conversations/26767901058

**Comment by xadamy** [comment]
Could it be that Elastic Beanstalk instances are (mis-)detected as containers? `cat /proc/meminfo` returns the correct amount of RAM, but cat /sys/fs/cgroup/memory/` returns an amount that is similar to what our users have been reporting:

```bash
[ec2-user@ip-x-x-x-x ~]$ cd /sys/fs/cgroup/memory/
[ec2-user@ip-x-x-x-x memory]$ cat memory.limit_in_bytes
9223372036854771712
[ec2-user@ip-x-x-x-x memory]$
```

This would seem to relate to https://github.com/appsignal/appsignal-agent/issues/364.
