### ISSUE TITLE
Report memory metrics as percentages

### ISSUE THREAD

**Issue by tombruijn** [appsignal/probes-rs#66]
Some metrics we only report as absolute numbers, but let's also try to report them as percentages as possible. Something which is more easy to set alerts on (but not necessarily better!).

## To do

⚠️ Important context: https://github.com/appsignal/probes-rs/issues/66#issuecomment-1641676269

- [ ] Add module for memory percentages based on the total available memory. Keep in mind that swap should not count towards the total used memory as it would probably result in percentages higher than 100%. (Or that is something we want?)
- [ ] Update this crate in the agent
- [ ] Report the exposed metrics as a __new metric__ name in the host metrics module, to avoid conflicts with the existing `memory` metric.
- [ ] Update memory trigger configuration to also support percentage based metrics.

**Comment by tombruijn** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700221387#part_id=comment-16410700221387-21909527151

**Comment by tombruijn** [comment]
Looks like we already collect the memory usage as a percentage already, but the calculation is done in the agent:

https://github.com/appsignal/appsignal-agent/blob/9c7aaf0d8397c67e85f41fec19cde0ffe14b302a/agent/src/host_metrics.rs#L208

We should still check if we want to report the other memory states as percentages too.

**Comment by luismiramirez** [comment]
I just added the free memory metric as a percentage here: https://github.com/appsignal/appsignal-agent/pull/1058

If we're OK with adding the swap > 100% metrics that can also be done. I'm not sure if it'll add much value.
