### ISSUE TITLE
Disk uage df fallback command not working?

### ISSUE THREAD

**Issue by tombruijn** [appsignal/probes-rs#75]
A user on Alpine Linux reports that they see no disk usage.

Narrowed it down to [this test setup](https://github.com/appsignal/test-setups/tree/d3fc3464076fac26bc3fc47f177e48bf962ef67f/ruby/sinatra-alpine). It installs the minimum required build packages "make gcc musl-dev musl-utils". (I've made this list smaller in [docs PR #1692](https://github.com/appsignal/appsignal-docs/pull/1692. The other packages shouldn't be necessary, and also include the GNU version of the `df` utility that works differently. That version of `df` works, but we shouldn't require people to install another version of the tool.)

The `df --local` command fails on Alpine Linux. The `df` command does work, but returns nothing. We see [this warning](https://github.com/appsignal/appsignal-agent/pull/1091): "No disk mountpoints found to report disk usage". This should not happen, this probes-rs library can't return an empty Vec for disk usage per mountpoint if the `df` command works. So I'm guessing the fallback isn't working properly.

- [Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/540709/conversation/16410700277360?view=List)
- [Support issue](https://github.com/appsignal/appsignal-agent/issues/1090)
- [Slack discussion](https://appsignal.slack.com/archives/C7XHXQ7N0/p1701945692903409)

**Comment by unflxw** [comment]
I haven't tested this, but I think the reason the fallback isn't working as expected is that, [on `disk_fs_local_raw`](https://github.com/appsignal/probes-rs/blob/main/src/disk_usage.rs#L183-L186), we do `cmd.output().map_err(…)?.stdout`, returning `Err(…)` if `.output()` was an error, or (eventually) returning `Ok()` if it wasn’t.

But [`.output()` only returns an error if it failed to execute the binary](https://doc.rust-lang.org/std/process/struct.Command.html#method.output), for example, if the binary does not exist, not if the execution results in a non-zero exit code. You have to [check `.status.success`](https://doc.rust-lang.org/std/process/struct.ExitStatus.html) on the struct returned by `.output()` for that.
